TodaysFail/TodaysFail-FE

.env
src/components/receipt/CopyModal.jsx
src/pages/NonUserSharePage/NonUserSharePage.jsx
src/pages/ReceiptPage/ReceiptPage.jsx
src/pages/SharePage/SharePage.jsx

feat: 환경변수 설정 및 영수증 페이지 공유하기 페이지 axios 호출 구조 변경

---

public/index.html

feat: og 태그 url 수정

---

src/pages/ReceiptPage/ReceiptPage.jsx

eslint 경고로 인한 console.log() 제거
Closes #{이슈 번호}

style: console.log() 제거

---

src/pages/ReceiptPage/ReceiptPage.jsx

feat: 영수증 페이지 date 및 nickname 변수 설정 변경

---

src/pages/MyPage/MyPage.jsx

기록하기 페이지 구현, css 수정
Closes #{이슈 번호}

style: background white

---

src/pages/MyPage/MyPage.jsx

메인페이지 긴 목록 scroll 가능하게
Closes #{이슈 번호}

style: scroll 가능하게

---

src/components/myPage/DailyFailureList.jsx
src/pages/MyPage/MyPage.jsx

style: 스크롤 수정

---

package-lock.json
src/pages/ReceiptPage/ReceiptPage.jsx

영수증 페이지 데이터 출력되는 순서를 변경합니다
- 기록하기 페이지의 역순으로 출력되는 것 확인
Closes #27

fix: 영수증 페이지 데이터 출력되는 순서 변경

---

src/pages/RecordPage/RecordPage.jsx

- 모바일 화면 상 하단 수정
- 타이머 위치 수정
기록하기 페이지 모바일 화면 디자인 수정
Closes #31

fix: 기록하기 페이지 모바일 화면 디자인 수정

---

src/components/receipt/FailCard.jsx
src/pages/ReceiptPage/ReceiptPage.jsx

fix: 영수증 페이지 디자인 수정

---

package-lock.json
package.json
src/App.js
src/api/apiController.jsx
src/components/common/Button.jsx
src/components/common/Modal.jsx
src/components/layout/MainLayout.jsx
src/components/myPage/DailyFailure.jsx
src/pages/ReceiptPage/ReceiptPage.jsx
src/router/Router.jsx

프론트엔트 공통 컴포넌트 분리 및 리팩토링
Closes #34

refactor: 공통 컴포넌트 및 API 인스턴스 분리, 레이아웃 설정

---

src/components/login/SignForm.jsx
src/pages/LoginPage/LoginPage.jsx
src/pages/RecordPage/RecordPage.jsx
src/utils/helpers/checkCurrentTime.js

로그인 페이지, 기록하기 페이지 리팩토링
utils 폴더 생성
Closes #38

refactor: 로그인 페이지 및 기록하기 페이지 리팩토링

---

src/reducers/recordListReducer.js

마이페이지 삭제 후 남은 기록 없을 때 '기록된 실패가 없어요' 뜨지 않는 버그 수정

[#39] fix: 마이페이지 삭제 후 남은 기록 없을 때 버그 수정

---

README.md
src/pages/RecordPage/RecordPage.jsx

리드미 작성
페이지 소개
주요 코드
등 추가하면 좋을 것 같아요
Closes #44

docs: 리드미 작성

---

src/pages/SharePage/SharePage.jsx

공유 페이지 주소 복사 로직 변경
clipboard API는 비동기적으로 동작해 promise 객체를 반환하기 때문에 then 메소드로 성공 시 동작을 컨트롤 할 수 있습니다
따라서 복사 되었을 때 모달창이 띄워져 복사를 확인할 수 있도록 변경하였습니다
Closes #49

refactor: clipboard API 특징 활용한 로직으로 변경

---

src/components/layout/MainLayout.jsx

로고 클릭 시 메인 페이지로 이동 (로그인 화면 제외)
Closes #{이슈 번호}

[#47] feat: 로고 클릭 시 메인 페이지로 이동

---

.env
.gitignore

remove: .env 삭제

---

src/pages/RecordPage/RecordPage.jsx

기록하기 페이지 작은 화면에도 맞게 수정
Closes #54

design: 기록하기 페이지 작은 화면에도 맞게 수정

---

src/components/login/ValidForm.jsx
src/pages/LoginPage/LoginPage.jsx

feat: 로그인 기능 구현

---

package-lock.json
package.json
src/components/signUp/SignUpForm.jsx
src/pages/SignUpPage/SignUpPage.jsx

회원가입 페이지의 기능을 구현합니다
버튼 공통 컴포넌트의 수정 필요
- 희원가입 페이지는 현재 disabled 속성 대신 모든 유효성 검사 통과 시에만 이벤트핸들링이 일어나도록 되어있어요! 공통 버튼 속성에 disabled 추가 후 disabled 속성에 따라 디자인 변경해야 할 것 같습니다 (로그인과 공통 사용)
Closes #57

feat: 회원가입 페이지 기능 구현

---

src/components/signUp/SignUpForm.jsx
src/pages/SignUpPage/SignUpPage.jsx

회원가입 페이지 에러메시지 및 글자수 변화 리팩토링
Closes #65

refactor: debounce 사용하여 회원가입 폼 입력시 상태 변화

---

src/components/signUp/SignUpButton.jsx
src/components/signUp/SignUpForm.jsx
src/pages/SignUpPage/SignUpPage.jsx

회원가입 페이지
- 회원가입 버튼 수정 (공통 컴포넌트 지금 사용하지 않고 디자인 시스템 나오면 추후 변경하는 것으로 논의)
- 인풋창 포커스 해제 시 다시 grey3 컬러로 전환되지 않는 현상 해결
Closes #67

fix: 버튼 수정 및 인풋 포커스 잃었을 때 디자인 변화

---

src/components/layout/MainLayout.jsx
src/components/myPage/DailyFailure.jsx
src/components/myPage/DailyFailureList.jsx
src/components/myPage/NoFailures.jsx
src/components/receipt/FailureCard.jsx
src/components/receipt/ReceiptShareContainer.jsx
src/pages/SharePage/SharePage.jsx

자랑하기 버튼 작성자 본인일 경우에만 보여주기, 기록 목록 페이지 및 레이아웃 높이 수정
마이페이지에 있던 overflow: scroll을 MainLayout으로 옮겼습니다!
[본인의 영수증 아닌 경우]
[본인의 영수증인 경우]
[기록된 실패가 없을 경우]
Closes #63

feat: 자랑하기 버튼 작성자 본인일 경우에만 보여주기

---

src/router/AuthRoute.jsx
src/router/Router.jsx
src/router/const.js

로그인 여부에 따라 라우팅 하기
Closes #{70}

feat: 로그인 여부에 따라 라우팅 하기

---

src/components/record/InputForm.jsx

fix: 수정하기 페이지 인풋영역 수정

---

package.json
src/api/apiController.jsx
src/pages/MyPage/MyPage.jsx
src/pages/RecordPage/RecordPage.jsx

- 빈 입력값 저장 시 경고 모달 구현
- 프록시 주소 변경
기록하기 페이지 입력 경고 모달 구현 및 프록시 테스트 주소로 변경
Closes #79

feat/fix: 기록하기 페이지 입력 경고 모달 구현 및 프록시 테스트 주소로 변경

---

src/pages/RecordPage/RecordPage.jsx

- 빈입력 시 기록 요청 분리하기
기록하기 페이지 빈입력 시 로직 수정
Closes #81

fix: 기록하기 페이지 빈입력 시 로직 수정

---

src/pages/LoginPage/LoginPage.jsx

- 엔터 키로 시작하기 구현
로그인 페이지 엔터 키로 시작하기 구현
Closes #88

feat: 로그인 페이지 엔터 키로 시작하기 구현

---

src/components/record/InputForm.jsx

- back space 영역 오류 수정
기록하기 페이지 back space 영역 오류 수정
Closes #90

fix: 기록하기 페이지 back space 영역 오류 수정

---

src/components/login/Form.jsx
src/pages/LoginPage/LoginPage.jsx

- 로그인 페이지 capslock 알림 구현
로그인 페이지 capslock 알림 구현
Closes #94

feat: 로그인 페이지 capslock 알림 구현
